### ISSUE TITLE
Unable to resolve dependencies

### ISSUE THREAD

**Issue by rob-gordon** [ananthakumaran/webify#17]
Trying to install yields the following:

	qupodogbark:little-sun-2 robgordon$ cabal install webify
	Resolving dependencies...
	cabal: Could not resolve dependencies:
	trying: webify-0.1.7.0 (user goal)
	trying: vector-0.11.0.0/installed-3c8... (dependency of webify-0.1.7.0)
	trying: primitive-0.6.1.0/installed-d71... (dependency of
	vector-0.11.0.0/installed-3c8...)
	next goal: optparse-applicative (dependency of webify-0.1.7.0)
	rejecting: optparse-applicative-0.12.1.0, 0.12.0.0, 0.11.0.2, 0.11.0.1,
	0.11.0, 0.10.0, 0.9.1.1, 0.9.1, 0.9.0, 0.8.1, 0.8.0.1, 0.8.0 (conflict: webify
	=> optparse-applicative>=0.5.2 && <0.8.0)
	rejecting: optparse-applicative-0.7.0.2, 0.7.0.1, 0.7.0, 0.6.0, 0.5.2.1, 0.5.2
	(conflict: primitive => transformers==0.4.2.0/installed-814...,
	optparse-applicative => transformers>=0.2 && <0.4)
	rejecting: optparse-applicative-0.5.1, 0.5.0, 0.4.3, 0.4.2, 0.4.1, 0.4.0,
	0.3.2, 0.3.1, 0.3.0, 0.2.0, 0.1.1, 0.1.0, 0.0.1 (conflict: webify =>
	optparse-applicative>=0.5.2 && <0.8.0)
	Dependency tree exhaustively searched.

I'm sorry if this an obvious error; a very new Haskell user.

**Comment by ananthakumaran** [comment]
What is your ghc version? If you want to just use the binary, I recommend you to download it from the release page https://github.com/ananthakumaran/webify/releases/tag/0.1.7.0

**Comment by rob-gordon** [comment]
Thanks, working well now!
